# Dev Dockerfile
FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache dumb-init

COPY package.json yarn.lock* ./

RUN yarn install --frozen-lockfile

COPY . .

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nuxt -u 1001

RUN chown -R nuxt:nodejs /app
USER nuxt

EXPOSE 3000

ENV NODE_ENV=development
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

# Start the development server
ENTRYPOINT ["dumb-init", "--"]
CMD ["yarn", "dev"]
